//! 3D Mesh Data Structures and Wavefront OBJ Exporter in Rust

use std::fs::File;
use std::io::{self, Write};
use std::path::Path;

#[derive(Debug, Clone, Copy)]
pub struct Vec3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl Vec3 {
    pub fn new(x: f32, y: f32, z: f32) -> Self {
        Self { x, y, z }
    }

    pub fn length(&self) -> f32 {
        (self.x * self.x + self.y * self.y + self.z * self.z).sqrt()
    }

    pub fn normalize(&self) -> Self {
        let len = self.length();
        if len > 1e-6 {
            Self::new(self.x / len, self.y / len, self.z / len)
        } else {
            *self
        }
    }

    pub fn cross(&self, other: &Self) -> Self {
        Self::new(
            self.y * other.z - self.z * other.y,
            self.z * other.x - self.x * other.z,
            self.x * other.y - self.y * other.x,
        )
    }

    pub fn dot(&self, other: &Self) -> f32 {
        self.x * other.x + self.y * other.y + self.z * other.z
    }

    pub fn add(&self, other: &Self) -> Self {
        Self::new(self.x + other.x, self.y + other.y, self.z + other.z)
    }

    pub fn sub(&self, other: &Self) -> Self {
        Self::new(self.x - other.x, self.y - other.y, self.z - other.z)
    }

    pub fn scale(&self, s: f32) -> Self {
        Self::new(self.x * s, self.y * s, self.z * s)
    }
}

#[derive(Debug, Clone, Copy)]
pub struct Vec2 {
    pub u: f32,
    pub v: f32,
}

impl Vec2 {
    pub fn new(u: f32, v: f32) -> Self {
        Self { u, v }
    }
}

#[derive(Debug, Clone)]
pub struct Face {
    pub indices: Vec<usize>, // 0-indexed vertex indices
}

#[derive(Debug, Clone)]
pub struct Mesh {
    pub name: String,
    pub vertices: Vec<Vec3>,
    pub normals: Vec<Vec3>,
    pub uvs: Vec<Vec2>,
    pub faces: Vec<Face>,
}

impl Mesh {
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            vertices: Vec::new(),
            normals: Vec::new(),
            uvs: Vec::new(),
            faces: Vec::new(),
        }
    }

    pub fn add_vertex(&mut self, v: Vec3) -> usize {
        let idx = self.vertices.len();
        self.vertices.push(v);
        idx
    }

    pub fn add_face(&mut self, indices: &[usize]) {
        self.faces.push(Face {
            indices: indices.to_vec(),
        });
    }

    /// Recompute smooth vertex normals based on adjacent face normals
    pub fn compute_vertex_normals(&mut self) {
        self.normals = vec![Vec3::new(0.0, 0.0, 0.0); self.vertices.len()];

        for face in &self.faces {
            if face.indices.len() >= 3 {
                let v0 = self.vertices[face.indices[0]];
                let v1 = self.vertices[face.indices[1]];
                let v2 = self.vertices[face.indices[2]];

                let edge1 = v1.sub(&v0);
                let edge2 = v2.sub(&v0);
                let face_normal = edge1.cross(&edge2).normalize();

                for &idx in &face.indices {
                    self.normals[idx] = self.normals[idx].add(&face_normal);
                }
            }
        }

        for normal in &mut self.normals {
            *normal = normal.normalize();
        }
    }

    /// Export the mesh to a standard Wavefront OBJ file
    pub fn export_obj<P: AsRef<Path>>(&self, path: P) -> io::Result<()> {
        let mut file = File::create(path)?;

        writeln!(file, "# Procedural 3D Model: {}", self.name)?;
        writeln!(file, "# Generated by Rust 3D Engine for EDITH & FRIDAY")?;
        writeln!(file, "o {}", self.name)?;

        // Write vertices
        for v in &self.vertices {
            writeln!(file, "v {:.6} {:.6} {:.6}", v.x, v.y, v.z)?;
        }

        // Write UVs
        for uv in &self.uvs {
            writeln!(file, "vt {:.6} {:.6}", uv.u, uv.v)?;
        }

        // Write normals
        for n in &self.normals {
            writeln!(file, "vn {:.6} {:.6} {:.6}", n.x, n.y, n.z)?;
        }

        // Write faces (1-indexed in OBJ format)
        for face in &self.faces {
            write!(file, "f")?;
            for &idx in &face.indices {
                let obj_idx = idx + 1;
                if !self.normals.is_empty() {
                    write!(file, " {}//{}", obj_idx, obj_idx)?;
                } else {
                    write!(file, " {}", obj_idx)?;
                }
            }
            writeln!(file)?;
        }

        Ok(())
    }
}
