"""
Pydantic schemas for AI Agent decision traces, turns, tool results, and execution records.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class StructuredDecision(BaseModel):
    """
    Auditable structured decision object generated by the agent planner (Section 25).
    Replaces hidden chain-of-thought with explicit, inspectable business rationale.
    """
    intent: str
    customer_goal: Optional[str] = None
    sales_stage: str
    confidence: float = Field(..., ge=0.0, le=1.0)
    important_context: List[str] = Field(default_factory=list)
    missing_information: List[str] = Field(default_factory=list)
    recommended_action: str  # 'question', 'recommend', 'handle_objection', 'quote_price', 'handoff', 'close'
    tools_required: List[str] = Field(default_factory=list)
    knowledge_required: List[str] = Field(default_factory=list)
    handoff_required: bool = False
    handoff_reason: Optional[str] = None
    followup_required: bool = False
    reason_code: str


class AgentTurnRequest(BaseModel):
    """Payload for directly triggering an agent turn (used in simulations and API tests)."""
    conversation_id: str
    inbound_message: str
    override_stage: Optional[str] = None
    is_simulation: bool = False


class AgentTurnResponse(BaseModel):
    """Response returned from an agent decision and reply cycle."""
    conversation_id: str
    reply_text: Optional[str] = None
    decision: StructuredDecision
    sales_stage_before: str
    sales_stage_after: str
    lead_score_before: int
    lead_score_after: int
    tools_executed: List[str] = Field(default_factory=list)
    handoff_created: bool = False
    is_suppressed: bool = False  # True if human takeover or paused
    invoice_pdf_path: Optional[str] = None


class AgentRunResponse(BaseModel):
    """Detailed record of an executed agent run for dashboard inspection (Section 110)."""
    id: str
    conversation_id: str
    message_id: Optional[str] = None
    model: str
    provider: str
    started_at: datetime
    completed_at: Optional[datetime] = None
    latency_ms: int
    intent: Optional[str] = None
    sales_stage_before: Optional[str] = None
    sales_stage_after: Optional[str] = None
    lead_score_before: Optional[int] = None
    lead_score_after: Optional[int] = None
    tools_used: List[Any] = Field(default_factory=list)
    knowledge_sources: List[Any] = Field(default_factory=list)
    decision_action: Optional[str] = None
    result_summary: Optional[str] = None
    error: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)
