"""
WatchdogAlert model for autonomous supervisor audits and operational health tracking (Section 125).
"""

from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Index, Integer, String, Text
from sqlalchemy.orm import relationship
from app.database.base import Base, OrgScopedMixin, TimestampMixin, UniversalJSON, generate_uuid, utc_now


class WatchdogAlert(Base, OrgScopedMixin, TimestampMixin):
    """
    Diagnostic alert generated by the Autonomous AI Watchdog (openai/gpt-oss-20b).
    Flags pricing anomalies, stalled dialogues, unresolved guardrail holds,
    and channel connectivity degradations.
    """
    __tablename__ = "watchdog_alerts"

    id = Column(String(64), primary_key=True, default=generate_uuid)
    severity = Column(String(32), default="warning", nullable=False)  # "info", "warning", "critical"
    category = Column(
        String(64), default="conversation_anomaly", nullable=False
    )  # "pricing_discrepancy", "stalled_chat", "guardrail_hold", "channel_latency", "system_health"
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)

    conversation_id = Column(String(64), ForeignKey("conversations.id", ondelete="SET NULL"), nullable=True, index=True)
    order_id = Column(String(64), ForeignKey("orders.id", ondelete="SET NULL"), nullable=True, index=True)

    metadata_payload = Column(UniversalJSON, default=dict, nullable=False)
    suggested_action = Column(Text, nullable=True)
    model_used = Column(String(128), default="openai/gpt-oss-20b", nullable=False)

    is_resolved = Column(Boolean, default=False, nullable=False, index=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    resolved_by = Column(String(128), nullable=True)

    conversation = relationship("Conversation", foreign_keys=[conversation_id])
    order = relationship("Order", foreign_keys=[order_id])
